// <auto-generated />
using System;
using Boardology.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Boardology.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190330220622_newest")]
    partial class newest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Boardology.API.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Created");

                    b.Property<int>("GameId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Boardology.API.Models.Downvote", b =>
                {
                    b.Property<int>("DownVoterId");

                    b.Property<int>("GameId");

                    b.HasKey("DownVoterId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Downvotes");
                });

            modelBuilder.Entity("Boardology.API.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AgeSuggestion");

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<int>("Downvotes");

                    b.Property<string>("Name");

                    b.Property<string>("NumPlayers");

                    b.Property<int>("NumReviews");

                    b.Property<string>("PhotoUrl");

                    b.Property<string>("TimeToPlay");

                    b.Property<int>("Upvotes");

                    b.Property<int>("YearCreated");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Boardology.API.Models.Upvote", b =>
                {
                    b.Property<int>("UpVoterId");

                    b.Property<int>("GameId");

                    b.HasKey("UpVoterId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("Upvotes");
                });

            modelBuilder.Entity("Boardology.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateJoined");

                    b.Property<string>("Email");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Boardology.API.Models.Comment", b =>
                {
                    b.HasOne("Boardology.API.Models.User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boardology.API.Models.Downvote", b =>
                {
                    b.HasOne("Boardology.API.Models.User", "DownVoter")
                        .WithMany()
                        .HasForeignKey("DownVoterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Boardology.API.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Boardology.API.Models.Upvote", b =>
                {
                    b.HasOne("Boardology.API.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Boardology.API.Models.User", "UpVoter")
                        .WithMany()
                        .HasForeignKey("UpVoterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
